### k-means algorithm


In [1]:
import numpy as np

#define number of clusters
k = 2

vectors = np.array([[5,3,7],[10,15,8],[15,12,10],[24,10,10],[30,45,20],[85,70,90],[71,80, 60],[60,78, 80],[55,52,40],[80,91,92]])

# for this example we choose the first k elements as initial centroids (instead of doing it randomly)
initial_centroids = vectors[:k] 

vector_length = len(vectors[0])

In [2]:
def calculate_distance(vectors, centroids):
    dists = -2 * np.dot(centroids, vectors.T) + np.sum(vectors**2, axis=1) + \
    np.sum(centroids**2, axis=1)[:, np.newaxis]
    
    return dists.T

#assign each vector to closest centroid

def centroid_assign_vectors(vectors, k, distances):
    
    # dictionary will contain each centroid as key, and all vectors which belong to its cluster
    cluster_dict = {c: [] for c in range(k)}

    for i,dis in enumerate(distances):
        # get the index of the shortest distance (the index corresponds to the centroid)
        min_dis_index = np.argmin(dis)
        cluster_dict[min_dis_index].append(vectors[i])
        
    return cluster_dict  

# calculate the new centroids

def calculate_new_centroids(cluster_dict, vector_length):
    updated_centroids = np.zeros(shape=(k,vector_length))

    for i, vectors in enumerate(cluster_dict.values()):
        # sum all of the vectors of each array
        stacked_array = np.vstack(vectors)
        # then calculate the mean
        new_centroid = np.ndarray.mean(stacked_array, axis=0) 
        updated_centroids[i] = new_centroid

    return updated_centroids


# using the functions defined above
def k_means(initial_centroids, vectors, vector_length):
    
    # start the first iteration with the initial centroids
    new_centroids = initial_centroids
    
    for i in range(20):
        print('iteration ', i)
        
        distances = calculate_distance(vectors, new_centroids)
        
        cluster_dict = centroid_assign_vectors(vectors, k, distances)
        
        updated_centroids = calculate_new_centroids(cluster_dict, vector_length)
        
        # check if vectors are not changing clusters anymore
        if np.array_equal(new_centroids, updated_centroids):
            return distances, cluster_dict, updated_centroids
            
        # if change is still occuring the centroids will be updated
        new_centroids = updated_centroids
    
    return distances, cluster_dict, updated_centroids

In [3]:
all_distances, cluster_dictionary, final_centroids = k_means(initial_centroids, vectors, vector_length)

iteration  0
iteration  1
iteration  2
iteration  3


In [4]:
final_centroids

array([[16.8, 17. , 11. ],
       [70.2, 74.2, 72.4]])

In [5]:
# shows which vector belongs to which cluster
cluster_dictionary

{0: [array([5, 3, 7]),
  array([10, 15,  8]),
  array([15, 12, 10]),
  array([24, 10, 10]),
  array([30, 45, 20])],
 1: [array([85, 70, 90]),
  array([71, 80, 60]),
  array([60, 78, 80]),
  array([55, 52, 40]),
  array([80, 91, 92])]}

In [6]:
# distance of each feature to each centroid
all_distances

array([[  351.24, 13597.64],
       [   59.24, 11276.04],
       [   29.24, 10809.64],
       [  101.84, 10149.84],
       [ 1039.24,  5214.44],
       [13701.24,   546.44],
       [ 9307.64,   188.04],
       [10348.24,   176.24],
       [ 3525.24,  1773.64],
       [16031.24,   762.44]])

This notebook uses the following example for k-means clustering:
https://stackabuse.com/k-means-clustering-with-scikit-learn/

Distance calculation: https://medium.com/@souravdey/l2-distance-matrix-vectorization-trick-26aa3247ac6c

In [7]:
# confirming the results from above

from sklearn.cluster import KMeans
import warnings
warnings.filterwarnings('ignore')

X = np.array([[5,3,7],[10,15,8],[15,12,10],[24,10,10],[30,45,20],[85,70,90],[71,80, 60],[60,78, 80],[55,52,40],[80,91,92],])

kmeans = KMeans(n_clusters=2, init = initial_centroids)
kmeans.fit(X)

print(kmeans.cluster_centers_)

[[16.8 17.  11. ]
 [70.2 74.2 72.4]]
